// GENERATED by scripts/design.mjs from docs/05-design/tokens.json. Do not edit.
// Run: node scripts/design.mjs tokens

export const themes = {
  "night": {
    "bg": "#080B10",
    "bgRaised": "#0E131A",
    "bgGlow": "#12304A",
    "glassFill": "rgba(160,196,255,0.055)",
    "glassFillStrong": "rgba(160,196,255,0.10)",
    "glassEdge": "rgba(196,222,255,0.14)",
    "glassHighlight": "rgba(255,255,255,0.09)",
    "divider": "rgba(196,222,255,0.08)",
    "scrim": "rgba(4,6,10,0.72)",
    "textPrimary": "#EDF2F7",
    "textSecondary": "#9AA8B8",
    "textTertiary": "#5E6B7A",
    "textDisabled": "#3B4552",
    "textOnAccent": "#061018",
    "accent": "#7CC8FF",
    "accentMuted": "rgba(124,200,255,0.16)",
    "focus": "#B9E0FF",
    "metric": {
      "speed": "#EDF2F7",
      "drive": "#FFB23F",
      "regen": "#3FE0B0",
      "voltage": "#A99BFF",
      "battery": "#3FE0B0",
      "temp": "#FF8A5B",
      "duty": "#7CC8FF",
      "gps": "#7CC8FF"
    },
    "state": {
      "ok": "#3FE0B0",
      "info": "#7CC8FF",
      "warn": "#FFC53D",
      "crit": "#FF4D5E",
      "stale": "#5E6B7A"
    }
  },
  "sun": {
    "bg": "#F4F6F8",
    "bgRaised": "#FFFFFF",
    "bgGlow": "#FFFFFF",
    "glassFill": "#FFFFFF",
    "glassFillStrong": "#E6EBF0",
    "glassEdge": "#1B2430",
    "glassHighlight": "rgba(0,0,0,0)",
    "divider": "#C9D1DA",
    "scrim": "rgba(10,14,20,0.55)",
    "textPrimary": "#05080C",
    "textSecondary": "#2E3A48",
    "textTertiary": "#5A6776",
    "textDisabled": "#A4AEB9",
    "textOnAccent": "#FFFFFF",
    "accent": "#0057B8",
    "accentMuted": "rgba(0,87,184,0.12)",
    "focus": "#0057B8",
    "metric": {
      "speed": "#05080C",
      "drive": "#B25E00",
      "regen": "#007A55",
      "voltage": "#4B2FD6",
      "battery": "#007A55",
      "temp": "#C23B0A",
      "duty": "#0057B8",
      "gps": "#0057B8"
    },
    "state": {
      "ok": "#007A55",
      "info": "#0057B8",
      "warn": "#9A6200",
      "crit": "#C4001A",
      "stale": "#7A8592"
    }
  }
} as const;

export const space = {
  "0": 0,
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 20,
  "6": 24,
  "8": 32,
  "10": 40
} as const;

export const radius = {
  "xs": 6,
  "sm": 10,
  "md": 14,
  "lg": 20,
  "pill": 999
} as const;

export const stroke = {
  "hairline": 1,
  "edge": 1,
  "gaugeTrack": 10,
  "gaugeValue": 10,
  "chartLine": 2
} as const;

export const grid = {
  "columns": 12,
  "rows": 6,
  "gap": 8,
  "padding": 10,
  "statusBarHeight": 30
} as const;

export const touch = {
  "minTarget": 48,
  "rideMinTarget": 56
} as const;

export const motion = {
  "valueTween": 90,
  "gaugeSpring": {
    "damping": 22,
    "stiffness": 260
  },
  "fast": 120,
  "base": 200,
  "sheet": 280,
  "bannerIn": 180,
  "critPulse": 900,
  "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
  "reducedMotion": "values jump without tween; no pulse; banners appear without slide"
} as const;

export const type = {
  "hero": {
    "font": "display",
    "size": 112,
    "weight": 600,
    "lineHeight": 0.9,
    "tracking": -2
  },
  "numXL": {
    "font": "display",
    "size": 64,
    "weight": 600,
    "lineHeight": 0.95,
    "tracking": -1
  },
  "numL": {
    "font": "display",
    "size": 40,
    "weight": 600,
    "lineHeight": 1,
    "tracking": -0.5
  },
  "numM": {
    "font": "display",
    "size": 28,
    "weight": 600,
    "lineHeight": 1,
    "tracking": 0
  },
  "numS": {
    "font": "display",
    "size": 20,
    "weight": 500,
    "lineHeight": 1.1,
    "tracking": 0
  },
  "unit": {
    "font": "ui",
    "size": 13,
    "weight": 500,
    "lineHeight": 1.2,
    "tracking": 0.2
  },
  "title": {
    "font": "ui",
    "size": 20,
    "weight": 600,
    "lineHeight": 1.25,
    "tracking": 0
  },
  "heading": {
    "font": "ui",
    "size": 15,
    "weight": 600,
    "lineHeight": 1.3,
    "tracking": 0
  },
  "body": {
    "font": "ui",
    "size": 14,
    "weight": 400,
    "lineHeight": 1.45,
    "tracking": 0
  },
  "label": {
    "font": "ui",
    "size": 11,
    "weight": 600,
    "lineHeight": 1.2,
    "tracking": 1.1,
    "case": "upper"
  },
  "caption": {
    "font": "ui",
    "size": 12,
    "weight": 400,
    "lineHeight": 1.35,
    "tracking": 0.1
  },
  "mono": {
    "font": "mono",
    "size": 12,
    "weight": 400,
    "lineHeight": 1.35,
    "tracking": 0
  }
} as const;

export const fonts = {
  "display": {
    "family": "Barlow Semi Condensed",
    "weights": [
      500,
      600,
      700
    ]
  },
  "ui": {
    "family": "IBM Plex Sans",
    "weights": [
      400,
      500,
      600
    ]
  },
  "mono": {
    "family": "IBM Plex Mono",
    "weights": [
      400,
      500
    ]
  }
} as const;

export const referenceScreen = {
  "widthDp": 915,
  "heightDp": 412,
  "minWidthDp": 732,
  "minHeightDp": 360,
  "orientation": "landscape"
} as const;

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };

/** Colour roles of one theme (night and sun share the names). */
export type Theme = Widen<typeof themes.night>;

/** Night is the default theme; the sun theme switch comes with settings. */
export const colors: Theme = themes.night;
