#!/usr/bin/env node
// Design tooling for docs/05-design. Usage:
//   node scripts/design.mjs tokens            tokens.json -> mockups/tokens.css + src/theme/tokens.ts
//   node scripts/design.mjs check             fail if tokens.css or tokens.ts is out of date
//   node scripts/design.mjs shots [name...]   screenshot every .frame[id] -> shots/<id>.png
//                                             (name filters by frame id or file, e.g. "dash-" or "history")
//   node scripts/design.mjs icons <dir>       rebuild mockups/icons.js from a lucide-static icons/ folder
// Shots need Playwright (`npm i -D playwright`, or a global install on NODE_PATH).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const designDir = path.join(root, 'docs/05-design');
const mockDir = path.join(designDir, 'mockups');
const shotDir = path.join(designDir, 'shots');
const tokens = JSON.parse(fs.readFileSync(path.join(designDir, 'tokens.json'), 'utf8'));

// Icon names used by the mockups. Same names as lucide-react-native components (kebab -> Pascal).
const ICONS = [
  'gauge', 'timer', 'history', 'bike', 'bell', 'settings', 'bluetooth', 'bluetooth-searching',
  'bluetooth-off', 'bluetooth-connected', 'satellite', 'circle-dot', 'thermometer', 'battery-medium',
  'battery-low', 'zap', 'activity', 'route', 'map-pin', 'cpu', 'layout-grid', 'plus', 'trash-2',
  'undo-2', 'check', 'x', 'chevron-right', 'chevron-left', 'chevron-down', 'triangle-alert',
  'octagon-alert', 'info', 'refresh-cw', 'flag', 'play', 'square', 'move', 'maximize-2', 'database',
  'hard-drive', 'archive', 'vibrate', 'volume-2', 'smartphone', 'sun', 'moon', 'ruler', 'lock',
  'sliders-horizontal', 'pencil', 'copy', 'layers', 'trending-down', 'wind', 'shield-check',
  'battery-warning', 'signal', 'mountain', 'clock', 'rotate-ccw', 'git-compare', 'menu', 'eye',
  'wrench', 'circle-help', 'power', 'battery-charging', 'thermometer-sun', 'navigation', 'link-2-off',
  'grip-vertical', 'target', 'flame', 'unplug', 'minus', 'scan-line', 'tag', 'globe',
];

const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

function buildCss() {
  const out = ['/* GENERATED by scripts/design.mjs from tokens.json. Do not edit. */'];
  const block = (sel, theme) => {
    const lines = [];
    for (const [k, v] of Object.entries(tokens.themes[theme])) lines.push(`--${kebab(k)}: ${v};`);
    for (const [k, v] of Object.entries(tokens.metric[theme])) lines.push(`--metric-${k}: ${v};`);
    for (const [k, v] of Object.entries(tokens.state[theme])) lines.push(`--state-${k}: ${v};`);
    out.push(`${sel} {\n  ${lines.join('\n  ')}\n}`);
  };
  block(':root, [data-theme="night"]', 'night');
  block('[data-theme="sun"]', 'sun');
  const shared = [];
  for (const [k, v] of Object.entries(tokens.space)) shared.push(`--space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(tokens.radius)) shared.push(`--radius-${k}: ${v}px;`);
  for (const [k, f] of Object.entries(tokens.font)) {
    if (f && f.family) shared.push(`--font-${k}: '${f.family}', ${f.fallback};`);
  }
  const g = tokens.grid;
  shared.push(`--grid-cols: ${g.columns};`, `--grid-rows: ${g.rows};`, `--grid-gap: ${g.gap}px;`,
    `--grid-pad: ${g.padding}px;`, `--status-h: ${g.statusBarHeight}px;`);
  shared.push(`--touch-min: ${tokens.touch.minTarget}px;`, `--touch-ride: ${tokens.touch.rideMinTarget}px;`);
  shared.push(`--motion-fast: ${tokens.motion.fast}ms;`, `--motion-base: ${tokens.motion.base}ms;`,
    `--motion-sheet: ${tokens.motion.sheet}ms;`, `--motion-ease: ${tokens.motion.easing};`);
  const rs = tokens['reference-screen'];
  shared.push(`--screen-w: ${rs.widthDp}px;`, `--screen-h: ${rs.heightDp}px;`);
  out.push(`:root {\n  ${shared.join('\n  ')}\n}`);
  for (const [k, t] of Object.entries(tokens.type)) {
    const ff = `var(--font-${t.font})`;
    const rules = [`font-family: ${ff};`, `font-size: ${t.size}px;`, `font-weight: ${t.weight};`,
      `line-height: ${t.lineHeight};`, `letter-spacing: ${t.tracking}px;`];
    if (t.case === 'upper') rules.push('text-transform: uppercase;');
    if (t.font === 'display') rules.push('font-variant-numeric: tabular-nums;');
    out.push(`.t-${kebab(k)} { ${rules.join(' ')} }`);
  }
  return out.join('\n') + '\n';
}

// App tokens for React Native / Skia: every value from tokens.json, nothing hand-written.
function buildTs() {
  const theme = (name) => ({ ...tokens.themes[name], metric: tokens.metric[name], state: tokens.state[name] });
  const pick = (obj) => Object.fromEntries(Object.entries(obj).filter(([k]) => k !== 'note'));
  const fonts = Object.fromEntries(
    Object.entries(tokens.font)
      .filter(([, f]) => f && f.family)
      .map(([k, f]) => [k, { family: f.family, weights: f.weights }]),
  );
  const parts = [
    ['themes', { night: theme('night'), sun: theme('sun') }],
    ['space', tokens.space],
    ['radius', tokens.radius],
    ['stroke', tokens.stroke],
    ['grid', pick(tokens.grid)],
    ['touch', pick(tokens.touch)],
    ['motion', tokens.motion],
    ['type', tokens.type],
    ['fonts', fonts],
    ['referenceScreen', tokens['reference-screen']],
  ];
  const body = parts.map(([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)} as const;`).join('\n\n');
  return (
    '// GENERATED by scripts/design.mjs from docs/05-design/tokens.json. Do not edit.\n' +
    '// Run: node scripts/design.mjs tokens\n\n' +
    body +
    '\n\ntype Widen<T> = { [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };\n\n' +
    '/** Colour roles of one theme (night and sun share the names). */\n' +
    'export type Theme = Widen<typeof themes.night>;\n\n' +
    '/** Night is the default theme; the sun theme switch comes with settings. */\n' +
    'export const colors: Theme = themes.night;\n'
  );
}

/** Lucide symbols from the mockup sprite as one SVG path string each (Skia draws them). */
function buildIconsTs() {
  const sprite = fs.readFileSync(path.join(mockDir, 'icons.js'), 'utf8').replace(/\\"/g, '"');
  const num = (el, k) => Number((el.match(new RegExp(`\\b${k}="([-\\d.]+)"`)) || [])[1] ?? 0);
  const toPath = (el) => {
    const tag = el.match(/^<(\w+)/)[1];
    if (tag === 'path') return el.match(/\bd="([^"]+)"/)[1];
    if (tag === 'line') return `M${num(el, 'x1')} ${num(el, 'y1')}L${num(el, 'x2')} ${num(el, 'y2')}`;
    if (tag === 'circle') {
      const [cx, cy, r] = [num(el, 'cx'), num(el, 'cy'), num(el, 'r')];
      return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0`;
    }
    if (tag === 'rect') {
      const [x, y, w, h, rx] = [num(el, 'x'), num(el, 'y'), num(el, 'width'), num(el, 'height'), num(el, 'rx')];
      if (!rx) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return `M${x + rx} ${y}h${w - 2 * rx}a${rx} ${rx} 0 0 1 ${rx} ${rx}v${h - 2 * rx}a${rx} ${rx} 0 0 1 ${-rx} ${rx}` +
        `h${-(w - 2 * rx)}a${rx} ${rx} 0 0 1 ${-rx} ${-rx}v${-(h - 2 * rx)}a${rx} ${rx} 0 0 1 ${rx} ${-rx}Z`;
    }
    if (tag === 'polyline' || tag === 'polygon') {
      const pts = el.match(/\bpoints="([^"]+)"/)[1].trim().split(/[\s,]+/);
      let d = '';
      for (let i = 0; i < pts.length; i += 2) d += `${i === 0 ? 'M' : 'L'}${pts[i]} ${pts[i + 1]}`;
      return tag === 'polygon' ? `${d}Z` : d;
    }
    throw new Error(`design: icon element <${tag}> not supported`);
  };
  const out = {};
  for (const [, name, body] of sprite.matchAll(/<symbol id="i-([a-z0-9-]+)" viewBox="0 0 24 24">(.*?)<\/symbol>/g)) {
    out[name] = (body.match(/<(path|line|circle|rect|polyline|polygon)\b[^>]*>/g) || []).map(toPath).join('');
  }
  return (
    '// GENERATED by scripts/design.mjs tokens from docs/05-design/mockups/icons.js. Do not edit.\n' +
    '// Lucide icons (ISC license) as SVG path strings on a 24 × 24 grid, stroked at width 2.\n\n' +
    `export const icons = ${JSON.stringify(out, null, 2)} as const;\n\n` +
    'export type IconName = keyof typeof icons;\n'
  );
}

const iconsTsPath = path.join(root, 'src/theme/icons.ts');
const tsPath = path.join(root, 'src/theme/tokens.ts');
const cssPath = path.join(mockDir, 'tokens.css');
const cmd = process.argv[2];
const args = process.argv.slice(3);

if (cmd === 'tokens') {
  fs.writeFileSync(cssPath, buildCss());
  fs.writeFileSync(tsPath, buildTs());
  fs.writeFileSync(iconsTsPath, buildIconsTs());
  console.log('design: wrote mockups/tokens.css, src/theme/tokens.ts and src/theme/icons.ts');
} else if (cmd === 'check') {
  const same = (p, text) => fs.existsSync(p) && fs.readFileSync(p, 'utf8') === text;
  const ok = same(cssPath, buildCss()) && same(tsPath, buildTs()) && same(iconsTsPath, buildIconsTs());
  if (!ok) { console.error('design: tokens.css, tokens.ts or icons.ts is stale. Run: node scripts/design.mjs tokens'); process.exit(1); }
  console.log('design: tokens in sync');
} else if (cmd === 'icons') {
  const dir = args[0];
  if (!dir) { console.error('usage: design.mjs icons <lucide-static>/icons'); process.exit(2); }
  const syms = ICONS.map((name) => {
    const svg = fs.readFileSync(path.join(dir, `${name}.svg`), 'utf8');
    const body = svg.replace(/<!--.*?-->/gs, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
      .replace(/\s+/g, ' ').trim();
    return `<symbol id="i-${name}" viewBox="0 0 24 24">${body}</symbol>`;
  });
  const js = `// GENERATED by scripts/design.mjs icons. Lucide icons (ISC license), same names as lucide-react-native.
// Usage in a mockup: <svg class="i"><use href="#i-gauge"/></svg>
(function () {
  var s = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' +
    ${JSON.stringify(syms.join(''))} + '</svg>';
  document.body.insertAdjacentHTML('afterbegin', s);
})();
`;
  fs.writeFileSync(path.join(mockDir, 'icons.js'), js);
  console.log(`design: wrote mockups/icons.js (${ICONS.length} icons)`);
} else if (cmd === 'shots') {
  let chromium;
  try { ({ chromium } = await import('playwright')); } catch {
    // ESM ignores NODE_PATH, so also look there (global installs).
    const req = createRequire(import.meta.url);
    for (const dir of (process.env.NODE_PATH || '').split(path.delimiter).filter(Boolean)) {
      try { ({ chromium } = req(req.resolve('playwright', { paths: [dir] }))); break; } catch { /* next */ }
    }
  }
  if (!chromium) {
    console.error('design: Playwright not found. npm i -D playwright (or set NODE_PATH to a global install).');
    process.exit(2);
  }
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1100, height: 900 }, deviceScaleFactor: 1 });
  fs.mkdirSync(shotDir, { recursive: true });
  const files = fs.readdirSync(mockDir).filter((f) => f.endsWith('.html') && f !== 'index.html').sort();
  let n = 0;
  for (const f of files) {
    await page.goto(pathToFileURL(path.join(mockDir, f)).href + '?shot=1');
    await page.evaluate(() => document.fonts.ready);
    const ids = await page.$$eval('.frame[id]', (els) => els.map((e) => e.id));
    for (const id of ids) {
      if (args.length && !args.some((a) => id.includes(a) || f.includes(a))) continue;
      await page.locator(`#${id}`).screenshot({ path: path.join(shotDir, `${id}.png`) });
      n++;
    }
  }
  await browser.close();
  console.log(`design: ${n} shot(s) in docs/05-design/shots/`);
} else {
  console.error('usage: node scripts/design.mjs tokens|check|shots [filter]|icons <dir>');
  process.exit(2);
}
